# create synthea providers for all eu countries

resources:
  repositories:
    - repository: synthea-international
      type: github
      endpoint: science-automation
      name: synthetichealth/synthea-international

trigger: none

pool:
  vmImage: 'ubuntu-latest'
 
jobs:
  - job: providers_generator
    timeoutInMinutes: 0
    steps:
    - checkout: self
      persistCredentials: true
    - checkout: synthea-international
      clean: true
    - script: |
        cd ${AGENT_BUILDDIRECTORY}/s
        rm -r -f synthea-international
        git clone https://scivm:$PASS@github.com/science-automation/synthea-international.git
      displayName: 'checkout from master and not detached head'
    - script: |
        pip install pandas
        pip install python-dotenv
        pip install requests
      displayName: 'Install python modules needed'
    - script: |
        cd ${AGENT_BUILDDIRECTORY}/s/genSyntheaEU/scripts
        echo "BASE_INPUT_DIRECTORY=${AGENT_BUILDDIRECTORY}/s/genSyntheaEU/data/healthsites" > .env
        echo "BASE_OUTPUT_DIRECTORY=${AGENT_BUILDDIRECTORY}/s/synthea-international" >> .env
        echo "BASE_REGION_DIRECTORY=${AGENT_BUILDDIRECTORY}/s/synthea-international" >> .env
        echo "HOSPITAL_BASE_ID=10000" >> .env
        echo "URGENT_CARE_BASE_ID=20000" >> .env
        echo "PRIMARY_CARE_BASE_ID=30000" >> .env
    - script: |
        cd ${AGENT_BUILDDIRECTORY}/s/genSyntheaEU/scripts
        git config --global user.name "scivm"
        git config http.version HTTP/1.1
        python genSyntheaProvider.py
        cd ${AGENT_BUILDDIRECTORY}/s/synthea-international
        git config --global user.name "scivm"
        git config http.version HTTP/1.1
        git add .
        git commit -m "generated from automation [skip ci]"
        git push -f https://scivm:$PASS@github.com/science-automation/synthea-international.git master
      env:
        PASS: $(gitpass)
        APIKEY: $(apikey)
      displayName: 'Generate providers from OSM data'
