# copy the synthea properties file into all countries
#
resources:
  repositories:
   - repository: synthea
     type: github
     endpoint: science-automation
     name: synthetichealth/synthea
   - repository: synthea-international
     type: github
     endpoint: science-automation
     name: synthetichealth/synthea-international

trigger: none

pool:
  vmImage: 'ubuntu-latest'
 
jobs:
  - job: tests_generator
    timeoutInMinutes: 0
    steps:
    - checkout: self
      persistCredentials: true
    - checkout: synthea-international
      clean: true
    - script: |
        pip install pandas
        pip install python-dotenv
      displayName: 'Install python modules needed'
    - script: |
        cd ${AGENT_BUILDDIRECTORY}/s/genSyntheaEU/scripts
        echo "BASE_INPUT_DIRECTORY=${AGENT_BUILDDIRECTORY}/s/synthea-international" > .env
      displayName: 'Prepare Run'
    - script: |
        cd ${AGENT_BUILDDIRECTORY}/s/genSyntheaEU/scripts
        python testall.py ${AGENT_BUILDDIRECTORY}
